//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBrandingSEO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int MaComment { get; set; }
        public Nullable<int> MaGiay { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string NoiDung { get; set; }
    
        public virtual Giay Giay { get; set; }
        public virtual Khachhang Khachhang { get; set; }
    }
}
