//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBrandingSEO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giay()
        {
            this.comments = new HashSet<comment>();
            this.CTDATHANGs = new HashSet<CTDATHANG>();
            this.Rates = new HashSet<Rate>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int MaGiay { get; set; }
        public string TenGiay { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string MoTa { get; set; }
        public string Hinh { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaNSX { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public Nullable<int> SoLuongTonKho { get; set; }
        public Nullable<int> Size { get; set; }
        public string mausac { get; set; }
        public string phai { get; set; }
        public Nullable<int> masale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDATHANG> CTDATHANGs { get; set; }
        public virtual LoaiGiay LoaiGiay { get; set; }
        public virtual Nhassanxuat Nhassanxuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate> Rates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
