//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBrandingSEO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profilegiohang
    {
        public int MaSave { get; set; }
        public int MaGiay { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> ngaycapnhat { get; set; }
        public int size { get; set; }
    
        public virtual SaveGioHang SaveGioHang { get; set; }
        public virtual Size Size1 { get; set; }
    }
}
