//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBrandingSEO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int MaSale { get; set; }
        public Nullable<int> MaGiay { get; set; }
        public Nullable<double> SalePhanTram { get; set; }
        public Nullable<decimal> SaleTien { get; set; }
        public Nullable<System.DateTime> ngaybatdau { get; set; }
        public Nullable<System.DateTime> NgayHetSale { get; set; }
    
        public virtual Giay Giay { get; set; }
    }
}
