//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBrandingSEO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Size()
        {
            this.profilegiohangs = new HashSet<profilegiohang>();
        }
    
        public int Masize { get; set; }
        public int MaGiay { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<int> TonKho { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual Giay Giay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profilegiohang> profilegiohangs { get; set; }
    }
}
